### ISSUE TITLE
Question: XOAUTH2 for a MailClient

### ISSUE THREAD

**Issue by nailuj29gaming** [Enough-Software/enough_mail#137]
How can I log into a `MaiLClient` with XOAUTH2?

**Comment by robert-virkus** [comment]
Thanks for pointing this out. I just pushed a commit with the high level `OauthAuthentication` option. 
In your `MailAccount` use this mechanism, e.g. 
```dart
mailAccount.incoming.authentication = OauthAuthentication('user-name', 'oauthtoken');
```
For you to be able to test this, you need to reference the GitHub version directly in your *pubspec.yaml*:
```
dependencies:
  enough_mail: 
    git:
      url: https://github.com/Enough-Software/enough_mail.git
```

Does this work for you?
