### ISSUE TITLE
No mailbox with flag MailboxFlag.sent found

### ISSUE THREAD

**Issue by Marco4763** [Enough-Software/enough_mail#170]
I can't access the Sent folder with the library, but I can on any other client email app, when I try to send an email with this library, I receive this response:

`Unhandled Exception: MailException: No mailbox with flag MailboxFlag.sent found in ["Lixo Eletrônico" exists: 0, highestModeSequence: null, "Itens Excluídos" exists: 0, highestModeSequence: null, "Itens Enviados" exists: 0, highestModeSequence: null, "Trash" exists: 0, highestModeSequence: null, "INBOX.spam" exists: 0, highestModeSequence: null, "Sent" exists: 0, highestModeSequence: null, "Drafts" exists: 0, highestModeSequence: null, "INBOX" exists: 4, highestModeSequence: 16].`

**Comment by robert-virkus** [comment]
Thanks for the report, what mail service are you using?
Also, would it be possible to test this again while depending on the git version of enough_mail? This should produce more output.
In your project, use this dependency:

```yaml
dependencies:
  enough_mail: 
    git:
      url: https://github.com/Enough-Software/enough_mail.git
```

I assume that you are using `MailClient.sendMessage(...)` which triggers this problem, is that correct?

**Comment by kunalmanocha98** [comment]
I am also facing a similar issue. There are no flags present in mailboxes list neither sent nor any other (draft,archive,junk etc..)

**Comment by kunalmanocha98** [comment]
> Thanks for the report, what mail service are you using? Also, would it be possible to test this again while depending on the git version of enough_mail? This should produce more output. In your project, use this dependency:
> 
> ```yaml
> dependencies:
>   enough_mail: 
>     git:
>       url: https://github.com/Enough-Software/enough_mail.git
> ```
> 
> I assume that you are using `MailClient.sendMessage(...)` which triggers this problem, is that correct?

But this is not compatible with enough_flutter and enough_editor

**Comment by robert-virkus** [comment]
I assume this is because the mail service in question does not support mailbox flags, [rfc 6154](https://datatracker.ietf.org/doc/html/rfc6154).
Can you confirm that this problem occurs when sending a message?

In regards to the dependencies, you can also alter the dependencies of enough_mail_flutter and enough_mail_html to target to the respective git repositories.

```yaml
dependencies:
  enough_mail: 
    git:
      url: https://github.com/Enough-Software/enough_mail.git
  enough_mail_flutter: 
    git:
      url: https://github.com/Enough-Software/enough_mail_flutter.git
  enough_mail_html: 
    git:
      url: https://github.com/Enough-Software/enough_mail_html.git
```
