### ISSUE TITLE
Mistake with Return-Path: when i send RETR 21

### ISSUE THREAD

**Issue by yarsort** [Enough-Software/enough_mail#191]
Hello. I have one problem...

![изображение](https://user-images.githubusercontent.com/54131603/169268386-289f2a6e-27cf-48dc-be16-759a125eeda6.png)

How i can receive body of letter with subject and attachments?

**Comment by robert-virkus** [comment]
Sorry, this is me to blame here. I have neglected POP3 support - this should now be fixed with 87ebcad55e4ad229d01500e97e107d395b34ec6f 

You can give it a test by using a git dependency override on `enough_mail` in your `pubspec.yaml`:

```yaml
dependency_overrides:
  xml: ^6.0.1
  enough_mail:
    git:
      url: https://github.com/Enough-Software/enough_mail.git
 ```

Once you confirmed the fix, I will publish a new release.
