### ISSUE TITLE
Unable to use with intl 0.18.0

### ISSUE THREAD

**Issue by tomyeh** [Enough-Software/enough_mail#210]
Due to the use of `^0.17.0` in enough_email's yaml, it is not possible to use with intl 0.18.0.

For example, `dart pub` will fail with the following setting.

```
name: Test

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  enough_mail: '^2.0.0'
  intl: '^0.18.0'
```
